### ISSUE TITLE
Add travis CI integration

### ISSUE THREAD

**Issue by inakianduaga** [Scout24/showcar-react#1]
# TODO

- [x] Generate tokens /  permissions / hook repo
- [x] Add .travis.yaml with configuration
- [ ] Push storybook bundle to gh-pages of different repo
  - follow instructions: https://github.com/storybooks/storybook-deployer
  - test locally first, if it works move to `.travis.yaml` for master branch only
